Fix linker includes
I got failures like these:

  libwiringPi.so: undefined reference to `pow'
  libwiringPi.so: undefined reference to `shm_open'

because we were missing -lm and -lrt in the Makefile. Add them.

Signed-off-by: Alexander Graf <agraf@suse.de>